subscribers:

  camera_reading:
    topic: /camera_nano/converted/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects_d

publishers:

  object_detector:
    topic: /darknet_ros/found_object_d
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes_d
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image_d/compressed
    queue_size: 1
    latch: true

image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: true
